export const ALL_DELIVERABLES = [
  { id: "VR-1", stream: "VR", title: "Simulation flow (entry → briefing → procedure → debrief)", owner: "PM", priority: "P0", sprint: "1", status: "In Spec", description: "End-to-end user journey through a clinical scenario: from launching the module, receiving a patient briefing, performing the procedure in VR, to the AI-generated debrief summary. This is the backbone flow every module depends on." },
  { id: "VR-2", stream: "VR", title: "Spatial UI menu system (11 screens)", owner: "Oluwatosin / Dr. Tara", priority: "P0", sprint: "1-2", status: "In Build", description: "Curved world-space canvas UI screens for Splash, Welcome, Dashboard, Platform, Modules, Module Detail, Simulation, Feedback, Results, Settings, and Help. Must be readable at 1.5m using raycast interaction." },
  { id: "VR-3", stream: "VR", title: "Onboarding flow for new users", owner: "Oluwatosin", priority: "P1", sprint: "3", status: "In Spec", description: "A 3-minute interactive tutorial that teaches new users how to teleport, grab objects, and interact with UI elements. Automatically triggers on first launch to reduce dropout." },
  { id: "VR-4", stream: "VR", title: "Scoring/grading rubric per scenario", owner: "PM + CSO", priority: "P0", sprint: "2", status: "In Spec", description: "Defines how each clinical scenario is scored: process adherence, safety compliance, execution quality, and efficiency. Rubric must be clinician-approved and transparent. Verified by Aladeojebi Adedotun Isaac." },
  { id: "VR-5", stream: "VR", title: "Session data schema", owner: "PM + Joshua", priority: "P0", sprint: "1", status: "In Spec", description: "JSON schema defining the data payload sent from VR to the backend after each session — includes session ID, user ID, module ID, timestamps, final score, FPS telemetry, and clinical event log." },
  { id: "VR-6", stream: "VR", title: "VR tutorial/guided walkthrough", owner: "Oluwatosin", priority: "P1", sprint: "3", status: "Not Started", description: "Step-by-step in-VR guide that walks users through the platform features: how to browse modules, check their stats, access settings, and start a scenario." },
  { id: "VR-7", stream: "VR", title: "Haptic feedback requirements", owner: "Oluwatosin", priority: "P1", sprint: "4", status: "Not Started", description: "Defines vibration patterns for controller feedback: confirmation pulses when grabbing tools, warnings on incorrect actions, and subtle feedback during interactions to increase immersion." },
  { id: "VR-8", stream: "VR", title: "Accessibility spec (comfort, subtitles, left-hand)", owner: "Dr. Tara", priority: "P1", sprint: "4", status: "In Spec", description: "P0 accessibility features: high-contrast subtitles pinned to lower field of view, seated/standing mode toggle, left/right hand dominance switch, and comfort vignetting during movement." },
  { id: "VR-9", stream: "VR", title: "Error/edge-case handling", owner: "Oluwatosin + Joshua", priority: "P1", sprint: "4", status: "Not Started", description: "Graceful handling of unexpected situations: app pauses when headset is removed, local cache saves session data if Wi-Fi drops, timeout recovery, and controller disconnection handling." },
  { id: "VR-10", stream: "VR", title: "Analytics event taxonomy", owner: "PM", priority: "P0", sprint: "1", status: "In Spec", description: "Master list of all trackable events fired from the VR app: module_started, tool_grabbed, step_completed, ai_query_sent, session_ended, etc. Each event has defined properties, PII flags, and owners." },
  { id: "VR-11", stream: "VR", title: "AI interaction model (Chat MoPT in VR)", owner: "Joshua + PM", priority: "P1", sprint: "3", status: "In Spec", description: "User presses left-wrist button to trigger voice recording sent to Chat MoPT. AI response displayed as floating subtitles in VR. Covers in-sim nudges and post-sim debrief interactions." },
  { id: "VR-12", stream: "VR", title: "Visual design system for VR", owner: "Dr. Tara", priority: "P1", sprint: "2", status: "In Spec", description: "Colour palette, typography scale, button styles, icon set, and spatial layout guidelines for all VR UI elements. Ensures visual consistency across all 11 screens and scenario environments." },
  { id: "VR-13", stream: "VR", title: "Content spec: full neonatal resus module", owner: "Dr. Olayinka + PM", priority: "P0", sprint: "2-3", status: "In Spec", description: "Complete clinical scenario for neonatal resuscitation: incubator environment, stethoscope, O2 tools, and medication interactions. Logic tree tracks user actions against Dr. Olayinka's rubric. Verified by Aladeojebi Adedotun Isaac." },
  { id: "VR-14", stream: "VR", title: "In-VR notification/alert system", owner: "Oluwatosin", priority: "P2", sprint: "4", status: "Not Started", description: "System for displaying alerts, warnings, and notifications inside VR: battery low, session time warnings, new module available, or system messages without breaking immersion." },
  { id: "VR-15", stream: "VR", title: "Performance benchmarks (72 FPS, load, memory)", owner: "Oluwatosin", priority: "P0", sprint: "1-4", status: "In Build", description: "Strict performance targets: minimum 72 FPS on Quest 3 at all times, max scene load time 4 seconds, enforced polycount and draw call budgets via Unity Profiler. Any PR dropping FPS below target is rejected." },
  { id: "VR-16", stream: "VR", title: "Multiplayer/collaborative mode", owner: "—", priority: "P2", sprint: "Post-Beta", status: "Not Started", description: "Future capability for multiple clinicians to participate in the same scenario simultaneously. Deferred post-beta — single-player is the priority for proving clinical value first." },
  { id: "VR-17", stream: "VR", title: "Session replay/review feature", owner: "Oluwatosin", priority: "P2", sprint: "Post-Beta", status: "Not Started", description: "Ability to replay a completed VR session for self-review or instructor observation. Critical for the offline replay evaluation pipeline and future ML model benchmarking." },
  { id: "VR-18", stream: "VR", title: "Offline mode requirements", owner: "Joshua + Oluwatosin", priority: "P1", sprint: "4", status: "In Spec", description: "When offline, completed session JSON payloads are queued locally on the headset and automatically uploaded when internet connection is restored. Ensures no data loss in poor-connectivity clinical environments." },
  { id: "VR-19", stream: "VR", title: "Voice interaction spec", owner: "Joshua", priority: "P2", sprint: "Post-Beta", status: "In Discovery", description: "Full voice-based interaction with Chat MoPT during scenarios — speech-to-text, LLM processing, text-to-speech response. ElevenLabs integration for natural clinical coaching voice." },
  { id: "VR-20", stream: "VR", title: "Update/patching mechanism (App Lab channels)", owner: "Oluwatosin", priority: "P1", sprint: "1", status: "In Build", description: "Automated build distribution via Meta App Lab's Alpha, Beta, and Production channels. Each channel maps to a Unity Cloud Build pipeline for seamless OTA updates." },
  { id: "VR-21", stream: "VR", title: "Device compatibility matrix", owner: "Dr. Tara", priority: "P1", sprint: "1", status: "In Spec", description: "Supported devices list with performance expectations: Quest 3 (primary, full features), Quest Pro (supported), Quest 2 (best-effort with potential feature reduction)." },
  { id: "VR-22", stream: "VR", title: "Beta test checklist + acceptance criteria", owner: "PM", priority: "P0", sprint: "5", status: "In Spec", description: "Comprehensive go/no-go checklist for Private Beta launch: 0 S1/S2 bugs, 72 FPS verified, DPIA signed, E2E round-trip validated over 50 sessions, KCL data sharing agreement executed." },
  { id: "VR-23", stream: "VR", title: "QA test plan for VR", owner: "PM (until QA hire)", priority: "P0", sprint: "5", status: "In Spec", description: "Manual exploratory test scripts for Quest 3 covering every scenario, UI flow, and edge case. Includes performance regression checks, cybersickness screening protocols, and accessibility validation." },
  { id: "VR-24", stream: "VR", title: "Data export spec (session → LMS)", owner: "Joshua", priority: "P0", sprint: "2", status: "In Spec", description: "Defines exactly how VR session data is packaged, encrypted, and transmitted to the LMS backend. Covers the JSON payload structure, authentication headers, retry logic, and idempotency requirements." },
  { id: "VR-25", stream: "VR", title: "Feature flag system spec", owner: "Joshua", priority: "P1", sprint: "3", status: "Not Started", description: "System for toggling features on/off without deploying new builds. Each flag has an owner and 90-day expiry. Critical kill-switch for Chat MoPT (ai.chat_mopt.enabled) must be hot-toggleable." },
  { id: "VR-26", stream: "VR", title: "In-VR user feedback mechanism", owner: "Oluwatosin", priority: "P1", sprint: "5", status: "In Spec", description: "Post-session 5-star rating prompt and 10-second voice-note bug report capability directly inside VR. Feedback flows into the central Notion/Dovetail repository for PM triage." },
  { id: "VR-27", stream: "VR", title: "Clinical content review/approval workflow", owner: "CSO + PM", priority: "P0", sprint: "2", status: "In Spec", description: "Formal sign-off process: every clinical scenario requires approval from Dr. Olayinka and verification by Aladeojebi Adedotun Isaac before merging to main. Version-locked to preserve historical grade accuracy." },
  { id: "Web-1", stream: "Web", title: "Review existing LMS (stack, features, API)", owner: "Joshua + PM", priority: "P0", sprint: "1", status: "In Build", description: "Full audit of the current LMS architecture: tech stack assessment, existing feature inventory, API surface review, and gap analysis against MoPT's requirements for VR data ingestion and analytics." },
  { id: "Web-2", stream: "Web", title: "Data contract: Unity ↔ LMS", owner: "Joshua + PM", priority: "P0", sprint: "1", status: "In Spec", description: "Formal agreement on the exact data formats, schemas, and protocols used between the Unity VR client and the LMS backend. This is the foundation every integration deliverable depends on." },
  { id: "Web-3", stream: "Web", title: "User authentication flow (VR client login)", owner: "Joshua", priority: "P0", sprint: "1", status: "In Spec", description: "OAuth 2.0 Device Flow (RFC 8628) implementation: VR headset displays a 6-digit pairing code, user authenticates on their phone at mopt.co.uk/link, VR receives JWT. No in-VR keyboard typing needed." },
  { id: "Web-4", stream: "Web", title: "Instructor dashboard wireframes", owner: "PM + Dr. Tara", priority: "P1", sprint: "3", status: "In Spec", description: "Dashboard for educators showing cohort performance table, red flags for students failing critical steps repeatedly, drill-down to individual Chat MoPT transcripts, and module assignment tools." },
  { id: "Web-5", stream: "Web", title: "Admin panel wireframes", owner: "PM", priority: "P1", sprint: "3", status: "In Spec", description: "Institution admin interface: seat utilization chart (e.g., 45/50 licenses active), invoice history, user management, GDPR data export button, and billing controls." },
  { id: "Web-6", stream: "Web", title: "Session data upload endpoint", owner: "Joshua", priority: "P0", sprint: "2", status: "In Build", description: "Backend API endpoint that receives completed VR session JSON payloads. Must handle authentication, validation, idempotent retries, and store data in PostgreSQL for dashboard consumption." },
  { id: "Web-7", stream: "Web", title: "Learner profile sync (Unity ↔ LMS)", owner: "Joshua", priority: "P1", sprint: "3", status: "In Spec", description: "Keeps learner profile data synchronized between the VR client and web LMS: display name, avatar, completed modules, certificates, and preferences. Ensures a consistent experience across platforms." },
  { id: "Web-8", stream: "Web", title: "Score/results submission endpoint", owner: "Joshua", priority: "P0", sprint: "2", status: "In Spec", description: "Dedicated endpoint for submitting scored results from the assessment engine. Separate from raw session data to support different processing pipelines and immediate dashboard updates." },
  { id: "Web-9", stream: "Web", title: "Individual learner performance view", owner: "Joshua + PM", priority: "P1", sprint: "3", status: "In Spec", description: "Web page showing a single learner's training history: spider chart of competencies across modules, score trends over time, earned certificates, and areas needing improvement." },
  { id: "Web-10", stream: "Web", title: "Cohort/class-level analytics view", owner: "Joshua + PM", priority: "P1", sprint: "4", status: "In Spec", description: "Aggregated analytics for an entire cohort: average scores, completion rates, common failure points, time-to-competency trends, and benchmarking against other cohorts." },
  { id: "Web-11", stream: "Web", title: "Module completion & progress tracking", owner: "Joshua", priority: "P1", sprint: "3", status: "In Spec", description: "Backend system tracking which modules each learner has started, completed, or abandoned. Powers the 'Continue Training' button and instructor visibility into student engagement." },
  { id: "Web-12", stream: "Web", title: "User role management (learner, instructor, admin)", owner: "Joshua", priority: "P1", sprint: "3", status: "In Spec", description: "Role-Based Access Control system: learners see their own data, instructors see their cohort, institution admins manage billing and seats, super admins edit clinical rubrics." },
  { id: "Web-13", stream: "Web", title: "Data privacy review (GDPR/DPIA)", owner: "DPO + PM", priority: "P0", sprint: "1-4", status: "In Build", description: "Formal Data Protection Impact Assessment required before beta launch. Covers PII handling, data residency (AWS London only), AI data processing agreements, consent mechanisms, and erasure endpoints." },
  { id: "Int-1", stream: "LMS", title: "Meet LMS team — integration points", owner: "PM + Joshua", priority: "P0", sprint: "1", status: "Done", description: "Initial discovery meeting to map all integration touchpoints between the Unity VR client, LMS backend, and web dashboard. Identifies data flows, authentication needs, and technical constraints." },
  { id: "Int-2", stream: "LMS", title: "API spec for Unity ↔ LMS", owner: "Joshua + PM", priority: "P0", sprint: "1", status: "In Build", description: "Complete API contract documentation: endpoints, methods, request/response schemas, authentication headers, rate limits, error codes, and versioning strategy. The single source of truth for all integration work." },
  { id: "Int-3", stream: "LMS", title: "Auth method (Device Flow recommended)", owner: "Joshua", priority: "P0", sprint: "1", status: "In Build", description: "Implementation of OAuth 2.0 Device Authorization Grant (RFC 8628). Eliminates the need for VR keyboard input — clinicians authenticate via phone/PC using a short pairing code displayed in the headset." },
  { id: "Int-4", stream: "LMS", title: "Unity-side API client", owner: "Oluwatosin", priority: "P0", sprint: "2", status: "In Build", description: "C# HTTP client library within the Unity project that handles all communication with the LMS: session submission, module fetching, auth token management, retry logic, and offline queuing." },
  { id: "Int-5", stream: "LMS", title: "Round-trip session data test", owner: "PM + Joshua", priority: "P0", sprint: "3", status: "Not Started", description: "End-to-end validation: complete a VR scenario, verify session data appears on the web dashboard within 5 seconds, confirm all scores, events, and telemetry are accurately transmitted and displayed." },
  { id: "Int-6", stream: "LMS", title: "Learner VR login flow test", owner: "PM", priority: "P0", sprint: "3", status: "Not Started", description: "Full user acceptance test of the Device Auth flow: generate pairing code in VR, enter on phone, verify JWT issued, confirm user identity loads correctly in the headset, and test token refresh." },
  { id: "Int-7", stream: "LMS", title: "Score submission & retrieval test", owner: "PM + Joshua", priority: "P0", sprint: "3", status: "Not Started", description: "Verify that assessment scores submitted from VR are correctly stored, retrievable via API, and displayed accurately on both learner and instructor dashboard views." }
];

export const ALL_RISKS = [
  { id: "R-01", category: "Technical", risk: "The VR app runs too slowly (below 72 frames per second), causing lag and motion sickness for users", score: 12, owner: "Oluwatosin", mitigation: "Enforce strict limits on 3D model complexity and visual effects. Run performance checks on every code change before it's approved." },
  { id: "R-02", category: "Technical", risk: "Users lose their training data if their Wi-Fi connection drops during a VR session", score: 16, owner: "Joshua (Tech Lead)", mitigation: "Save session data locally on the headset first, then upload when internet returns. All uploads are designed to be safely retried without creating duplicates." },
  { id: "R-03", category: "Product / Clinical", risk: "The AI assistant (Chat MoPT) invents incorrect medical advice, teaching clinicians the wrong thing", score: 15, owner: "Joshua + Aladeojebi Adedotun Isaac", mitigation: "Lock AI creativity to zero for medical facts. Only allow answers sourced from verified NHS/NICE guidelines. Run a second AI check on every response before showing it to users." },
  { id: "R-04", category: "Regulatory", risk: "An NHS hospital wants to buy MoPT but we haven't completed the required safety and technology assessments (DTAC) yet", score: 16, owner: "PM + Data Protection Officer", mitigation: "Prepare the full compliance evidence pack before beta launch. Formally appoint a Clinical Safety Officer. Have everything ready to submit within 5 working days of any buyer request." },
  { id: "R-05", category: "Data / Security", risk: "A data breach exposes users' personal information (names, emails, performance records)", score: 10, owner: "Data Protection Officer", mitigation: "Store all data exclusively in UK servers. Encrypt everything. Follow industry security standards. Run regular security audits by external experts. Limit data access to only those who need it." },
  { id: "R-06", category: "Compliance", risk: "A user files a formal privacy complaint with the UK's data regulator (ICO)", score: 8, owner: "Data Protection Officer", mitigation: "Get clear consent from every user. Build a system for users to easily request their data or delete their account. Respond to any regulator contact within 24 hours." },
  { id: "R-07", category: "Clinical Safety", risk: "A training scenario accidentally teaches clinicians the wrong medical procedure", score: 10, owner: "Aladeojebi Adedotun Isaac (Medical Verifier)", mitigation: "Require sign-off from at least 2 independent medical experts before any scenario goes live. Lock the version so student grades stay accurate even if the scenario is later updated." },
  { id: "R-08", category: "Team", risk: "Our only Unity/VR developer (Oluwatosin) becomes unavailable, halting all VR development", score: 16, owner: "COO", mitigation: "Document all architecture decisions and code patterns. Start recruiting a second VR developer. Keep a contractor agency on standby for emergencies." },
  { id: "R-09", category: "Team", risk: "Our sole backend/web developer (Joshua) becomes unavailable, blocking web and API work", score: 12, owner: "COO", mitigation: "Hire a platform engineer to share the load. Create runbooks for all critical systems. Establish paired on-call responsibility." },
  { id: "R-10", category: "Commercial", risk: "No hospital or university signs up for a paid pilot programme after beta", score: 12, owner: "CEO + PM", mitigation: "Start sales conversations 6 weeks before beta ends. Prepare a comprehensive evidence pack (Trust Center) that removes procurement friction. Have proof of learning outcomes ready." },
  { id: "R-11", category: "Market", risk: "A competitor launches an AI-powered clinical training product before us", score: 9, owner: "PM", mitigation: "Move fast on our unique differentiator (assessment intelligence). Lean on our clinical evidence and real learning outcome data rather than competing on features alone." },
  { id: "R-12", category: "Hardware", risk: "Meta releases a headset software update that breaks our VR app", score: 6, owner: "VR Lead", mitigation: "Lock headset software versions through device management tools. Maintain a direct relationship with Meta's developer support. Have a hotfix process ready to respond quickly." },
  { id: "R-13", category: "Supplier", risk: "Our AI provider (e.g., OpenAI) has a major outage or changes their terms of service", score: 12, owner: "Joshua (Tech Lead)", mitigation: "Build the system so we can swap AI providers easily. Always have a backup provider ready. Set cost limits per session. If AI is down, fall back to pre-written feedback templates." },
  { id: "R-14", category: "Financial", risk: "AI processing costs per session are higher than expected, eating into our profit margins", score: 9, owner: "COO + Alexander Olaiya (ML/AI)", mitigation: "Set hard limits on AI usage per session. Cache common questions and answers. Monitor cost per session weekly. Explore cheaper open-source AI models after beta." },
  { id: "R-15", category: "Reputational", risk: "A clinician posts a negative viral review of MoPT on social media", score: 8, owner: "CEO", mitigation: "Provide excellent support so problems are resolved before they escalate. Have a PR response plan ready. CEO responds personally with transparency and offers to make it right." },
  { id: "R-16", category: "IP", risk: "A medical expert we hired to create scenario content claims ownership of that content", score: 6, owner: "Graham (IP Lawyer) + PM", mitigation: "Sign clear content agreements upfront stating MoPT owns all created content. Credit and offer royalties to experts for premium content. Have IP counsel review all agreements." },
  { id: "R-17", category: "Operational", risk: "VR headsets lent to a hospital get lost, stolen, or damaged", score: 6, owner: "Customer Success Manager", mitigation: "Enroll all headsets in remote device management (can remotely wipe if stolen). Keep a serial-numbered asset register. Guide institutions to cover headsets under their equipment insurance." },
  { id: "R-18", category: "Ethical / AI", risk: "The virtual patients in our scenarios lack diversity, potentially training bias into clinicians", score: 12, owner: "PM + Clinical Advisory Board", mitigation: "Conduct formal bias reviews on all virtual patient avatars. Ensure diverse representation across ethnicity, gender, age, and body type. Get external peer audit on our content." },
  { id: "R-19", category: "Legal", risk: "Lengthy negotiations over data processing agreements delay launch with a hospital", score: 9, owner: "COO + Graham (IP Lawyer)", mitigation: "Pre-draft standard data processing and service level agreements. Aim to complete legal negotiations within 2 weeks. Escalate to CEO-to-CEO calls if blocked beyond 3 weeks." },
  { id: "R-20", category: "Content", risk: "We can't create new training scenarios fast enough to meet demand", score: 12, owner: "PM", mitigation: "Hire a dedicated Clinical Content Designer. Standardize the scenario creation pipeline. If still bottlenecked, outsource module creation to vetted external medical authors." }
];

export const ALL_OKRS = [
  {
    id: "O1",
    objective: "Earn the right to sell to the NHS.",
    keyResults: [
      "Complete DPIA and DCB0129 Clinical Safety Case.",
      "Achieve Cyber Essentials Plus certification.",
      "Submit DTAC pack to 1 NHS Trust buyer."
    ],
    owner: "PM + DPO + CSO"
  },
  {
    id: "O2",
    objective: "Prove learning outcomes in a clinical cohort.",
    keyResults: [
      "Run Private Beta with >=20 KCL clinicians.",
      "Demonstrate >=20% competency-score improvement (Kirkpatrick L2) across 3 attempts.",
      "Achieve Institutional NPS >=40."
    ],
    owner: "PM + Clinical Lead"
  },
  {
    id: "O3",
    objective: "Build a commercial, scalable platform.",
    keyResults: [
      "Sign 2 paid institutional pilots (£5-15k ARR each).",
      "Keep unit gross margin >=70% after LLM costs.",
      "Ship v1.0 scenario authoring pipeline used to release 3 modules."
    ],
    owner: "PM + COO"
  }
];

export const TEAM_MEMBERS = [
  { name: "Dr. Olayinka Kowobari", role: "CEO / Clinical Lead", area: "Leadership" },
  { name: "Adetola", role: "CFO / COO", area: "Leadership" },
  { name: "Dr. Tara", role: "VR Academic Lead / UX", area: "VR" },
  { name: "Joshua", role: "VR / Tech Lead", area: "Engineering" },
  { name: "Alexander Olaiya", role: "ML/AI Engineer", area: "AI/ML" },
  { name: "Matt", role: "ML/AI Engineer (Classical ML & CV)", area: "AI/ML" },
  { name: "Aladeojebi Adedotun Isaac", role: "Medical Verifier / Clinical Safety", area: "Clinical" },
  { name: "Prof. Adedayo Olaosun", role: "Clinical Advisory Board Chair", area: "Clinical" },
  { name: "Graham Spenceley", role: "IP / Legal Counsel", area: "Legal" },
  { name: "Dr. Janice Turner", role: "Product Advisory Board Chair", area: "Advisory" },
  { name: "Gigi Brett", role: "Business Advisor", area: "Advisory" },
  { name: "Ayokunnu Olaogun", role: "Finance Advisor", area: "Advisory" },
];

export const SPRINT_PLAN = [
  { sprint: "1", theme: "Foundation", weeks: "Wk 1–2", deliverables: "API contracts locked; Device Auth live; Spatial UI shell; LMS audit complete; DPIA kicked off.", exit: "Clinician can pair headset with web and load Platform menu." },
  { sprint: "2", theme: "Core Simulation", weeks: "Wk 3–4", deliverables: "Neonatal resus scene; Scoring rubric; Session schema; /sessions endpoint.", exit: "Module playable locally; 200 OK on session POST." },
  { sprint: "3", theme: "Integration + AI", weeks: "Wk 5–6", deliverables: "Round-trip data (VR → LMS → Dashboard); Chat MoPT RAG baseline; Individual learner view.", exit: "Completed module in VR appears on web within 5s; Chat MoPT debrief functional." },
  { sprint: "4", theme: "Hardening", weeks: "Wk 7–8", deliverables: "72 FPS guarantee; haptics; accessibility; edge cases; offline cache; feature flags; Clinical Safety Case draft.", exit: "OVR metrics green; app recovers from Wi-Fi drop; CSO approves safety case." },
  { sprint: "5", theme: "Beta Readiness", weeks: "Wk 9–10", deliverables: "QA sweep; GDPR walkthrough; train-the-trainer kit; KCL onboarding docs; App Lab Beta channel push.", exit: "Zero S1/S2; DPIA signed; KCL accounts provisioned; beta communication sent." },
];
